plugins:
  - jekyll-paginate
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge
paginate: 3
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      lang: "en"
