markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 3
paginate_path: "/blog/page:num/"

permalink: /blog/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      lang: "en"
